### ISSUE TITLE
Could not find generator 'langchainrb_rails:pgvector' if you follow instructions

### ISSUE THREAD

**Issue by palladius** [andreibondarev/langchainrb_rails#20]
HI, I created a new rails installation and got this.
Both with gem install and bundle install, it doesnt find the generator.

```
$ rails generate langchainrb_rails:pgvector --model=Product --llm=openai
Could not find generator 'langchainrb_rails:pgvector'. (Rails::Command::Base::CorrectableError)
Run `bin/rails generate --help` for more options.
```

Maybe there are some prerequisite to the created rails repo? I've used
* ruby 3.2.1
* rails 7.0.8

App is available/reproable here: https://github.com/palladius/langchainrb_rails_test

**Comment by andreibondarev** [comment]
@palladius It works with my app on rails 7.0.4.3 / ruby 3.1.2. I'll have to dive in a bit deeper. Odd.

**Comment by andreibondarev** [comment]
@palladius I just realized that your [Gemfile](https://github.com/palladius/langchainrb_rails_test/blob/main/Gemfile) is missing `langchainrb_rails` gem. I think if you add it, bundle install, it should just work!
