### ISSUE TITLE
Issue with Product.ask 

### ISSUE THREAD

**Issue by nocode66** [andreibondarev/langchainrb_rails#26]
3.2.2 :003 > Product.ask("list the brands of shoes that are in stock")
/.rvm/gems/ruby-3.2.2/gems/langchainrb_rails-0.1.5/lib/langchainrb_overrides/vectorsearch/pgvector.rb:108:in `ask': wrong number of arguments (given 0, expected 1) (ArgumentError)

**Comment by andreibondarev** [comment]
Can you try Product.ask(question: "...")?

**Comment by nocode66** [comment]
same thing

**Comment by nocode66** [comment]
in ask method I see the following: 
lib/langchainrb_overrides/vectorsearch/pgvector.rb

line 111: 
`search_results = similarity_search(query: question, k: k)`

I think it mayght be: 
`search_results = self.similarity_search(query: question, k: k)`

also I didn't find generate_rag_prompt method definition

**Comment by andreibondarev** [comment]
@nocode66 The definition of [generate_rag_prompt()](https://github.com/andreibondarev/langchainrb/blob/e5270fbaec94f37bc9c20c0a1219c59c4764e95b/lib/langchain/vectorsearch/base.rb#L171-L176). I'll try  and recreate the your issue with the `ask()` method and get back to you!

**Comment by ddyy** [comment]
Made a PR for this: https://github.com/andreibondarev/langchainrb_rails/pull/27

**Comment by andreibondarev** [comment]
@nocode66 It should be fixed now on `main`!
