### ISSUE TITLE
OpenAI HTTP Error with default install

### ISSUE THREAD

**Issue by chalmagean** [andreibondarev/langchainrb_rails#56]
After installing the gem, and running the migrations, I'm getting the following error on save.

```
OpenAI HTTP Error (spotted in ruby-openai 6.3.1): {"error"=>{"message"=>"This model does not support specifying dimensions.", "type"=>"invalid_request_error", "param"=>nil, "code"=>nil}}
```

This doesn't seem like a nice developer experience since it breaks the app.

I also couldn't find any documentation on how to fix the issue.

**Comment by andreibondarev** [comment]
@chalmagean I agree, I'm going to try and fix it this week. Sorry about that! :(

**Comment by chalmagean** [comment]
Let me know if there's anything I can do to help.

**Comment by andreibondarev** [comment]
@chalmagean I just published a new version: 0.1.8. Would you please give it a spin and see how it works for you?

**Comment by chalmagean** [comment]
This is working great now. Thank you 🙏

**Comment by andreibondarev** [comment]
@chalmagean I'd love any other feedback!
